### ISSUE TITLE
HTTPing and Homebrew

### ISSUE THREAD

**Issue by iandol** [folkertvanheusden/HTTPing#3]
httping has been disabled for install using homebrew on macOS and Linux due to the upstream repo being removed. Is this repo the future home for httping?

https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/httping.rb

```
disable! date: "2022-10-19", because: :repo_removed
```

**Comment by folkertvanheusden** [comment]
Correct!

**Comment by iandol** [comment]
@folkertvanheusden — are you planning to use releases and tags / versioning? Is the code here equivalent to the V2.5 code floating around? This may help packaging tools like homebrew.

**Comment by ryandesign** [comment]
> Ah, I just found the version file, V2.6...

v2.9 was released 4 days after your comment.

>> Is this repo the future home for httping?
>
> Correct!

Could you elaborate, please?

Why was the previous GitHub repository and the entire GitHub account flok99 removed?

Why was the project resumed?

Why does this new repository contain only 11 commits and 1 tag? What happened to the 337 commits and 15 tags from the old repository?

Why does the [current homepage](https://web.archive.org/web/20230515215808/https://www.vanheusden.com/httping/) appear outdated compared to the [2021 version of the homepage](https://web.archive.org/web/20210212054801/https://www.vanheusden.com/httping/)? (The 2021 homepage stated the current version was 2.5; the current homepage says the current version is 1.5.)

What changed between versions 2.5 and 2.9? What happened to versions 2.6, 2.7, and 2.8? I can't check the nonexistent commit history or tags and there is no changelog or news file. I looked at the diff between the 2.5 and 2.9 tarballs, which fortunately wasn't too large, and I didn't see too many changes, though I do notice the license file changed from AGPL 3 with OpenSSL exception to GPL 3 with no mention of OpenSSL exception. I don't see an indication of whether this is intended to be GPL-3-only or GPL-3-or-later. The comments at the tops of the source files have not been adjusted and still say AGPL 3 with OpenSSL exception. The GPL 3 license file looks like it could have been a mistake, since it was committed by itself as the first commit in the new repo.

I tried to get the answers to these questions by following the link on the homepage to a discussion mailing list, but it's 404 not found. The last post on the [archived version of that discussion list](https://web.archive.org/web/20151004052519/http://keetweej.vanheusden.com/httping/) was from the release of version 2.4, too old to answer my questions.

The current readme only has 4 non-empty lines, 2 of which are broken images to broken links. The version 2.5 readme was 47 lines long and contained useful installation and usage information.

All of this and the lack of a provided explanation for it is very suspicious and makes me very wary of switching httping in MacPorts to this new source.

**Comment by folkertvanheusden** [comment]
The previous releases/website/etc were deleted due to personal reasons.

The versions currently on the website/github are all I have left. If you
have something more recent, please let me know.
